/* Configured numerical models and an explicit student investigation notebook. */
(()=>{'use strict';
const root=document.querySelector('#investigations');if(!root)return;
const labs=JSON.parse(document.querySelector('#investigation-data').textContent),profile=PRACTICE_CATALOG.profile,store=StudentLearningState;
const el=(tag,text,p)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;p?.append(e);return e;};
const button=(p,text,fn)=>{const b=el('button',text,p);b.type='button';b.onclick=fn;return b;};
const notice=el('p','',root);notice.setAttribute('role','status');let state;try{state=store.read(profile);}catch{state={schema:1,plans:{},notebooks:{},practice:null};notice.textContent='Saving is unavailable. Export your notebook before leaving.';}
const chooser=el('select','',el('label','Choose an investigation',root));chooser.setAttribute('aria-label','Choose an investigation');labs.forEach(l=>el('option',l.title,chooser).value=l.id);const area=el('div','',root);
function save(){try{store.save(profile,state);notice.textContent='Notebook saved in this browser.';}catch{notice.textContent='Could not save. Export your notebook before leaving.';}}
function model(l,p){if(l.model==='product')return l.coefficient*Object.entries(l.powers).reduce((v,[k,power])=>v*p[k]**power,1);if(l.model==='approach')return p[l.amplitude]*(1-Math.exp(-p[l.rate]*p[l.x]));if(l.model==='line')return p[l.slope]*p[l.x]+p[l.intercept];if(l.model==='polynomial')return l.coefficients.reduce((v,c,i)=>v+c*p[l.x]**i,0);throw Error('Unknown model.');}
function draw(){area.replaceChildren();const lab=labs.find(l=>l.id===chooser.value),params=Object.fromEntries(lab.parameters.map(p=>[p.id,p.value])),notebook=state.notebooks[lab.id]||{prediction:'',conclusion:'',rows:[],check:'',checked:false};state.notebooks[lab.id]=notebook;el('h1',lab.title,area);el('p',lab.topic+' · '+lab.question,area);el('p','Skills: '+lab.skills.map(s=>PRACTICE_CATALOG.skill_labels[s]||s).join(' · '),area);
 const prediction=el('textarea','',el('label','1. Predict what will happen',area));prediction.maxLength=4000;prediction.value=notebook.prediction;prediction.oninput=()=>{notebook.prediction=prediction.value;save();};el('h2','2. Collect evidence',area);el('p',lab.method,area);
 const controls=el('div','',area);controls.className='panel';const outputs=new Map();lab.parameters.forEach(p=>{const l=el('label',p.label,controls),input=el('input','',l);input.type='range';input.min=p.min;input.max=p.max;input.step=p.step;input.value=p.value;input.setAttribute('aria-label',p.label);if(p.min===p.max)input.disabled=true;const output=el('output',String(p.value),l);outputs.set(p.id,output);input.oninput=()=>{params[p.id]=Number(input.value);output.textContent=input.value;live.textContent='Model value: '+model(lab,params).toPrecision(4)+' · '+lab.yLabel;};});const live=el('p','Model value: '+model(lab,params).toPrecision(4)+' · '+lab.yLabel,controls);
 const result=el('p','',area);result.setAttribute('role','status');const graph=el('div','',area),table=el('div','',area);table.className='table-scroll';
 button(controls,'Record measurement',()=>{if(notebook.rows.length>=60){result.textContent='60 readings saved. Export and clear before recording more.';return;}const noise=lab.noiseParameter?params[lab.noiseParameter]:lab.noise;const y=model(lab,params)+(Math.random()*2-1)*(noise||0);notebook.rows.push({x:params[lab.x],y:Number(y.toPrecision(6)),params:{...params}});notebook.checked=false;save();renderReadings();});
 button(controls,'Clear readings',()=>{if(notebook.rows.length&&!confirm('Clear these readings? Export your notebook first to keep this run.'))return;notebook.rows=[];notebook.checked=false;save();renderReadings();});
 function renderReadings(fit){graph.replaceChildren();table.replaceChildren();const rows=notebook.rows;if(!rows.length){el('p','Record a measurement to start your graph.',graph);return;}const t=el('table','',table),head=el('tr','',el('thead','',t));[lab.xLabel,lab.yLabel,'Other settings',''].forEach(s=>el('th',s,head));const body=el('tbody','',t);rows.forEach((r,i)=>{const tr=el('tr','',body);el('td',String(r.x),tr);el('td',String(r.y),tr);el('td',lab.parameters.filter(p=>p.id!==lab.x).map(p=>p.label+': '+r.params[p.id]).join(' · '),tr);button(el('td','',tr),'Remove reading '+(i+1),()=>{notebook.rows.splice(i,1);notebook.checked=false;save();renderReadings();});});
 const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 640 340');svg.setAttribute('role','img');svg.setAttribute('aria-label','Scatter plot of recorded measurements; exact readings in the table below.');svg.classList.add('graph');graph.append(svg);function shape(tag,attrs,text){const e=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text)e.textContent=text;svg.append(e);}
 const xmin=Math.min(...rows.map(r=>r.x)),xmax=Math.max(...rows.map(r=>r.x)),ymin=Math.min(0,...rows.map(r=>r.y)),ymax=Math.max(1,...rows.map(r=>r.y));const X=x=>65+(x-xmin)/(xmax-xmin||1)*540,Y=y=>280-(y-ymin)/(ymax-ymin||1)*240;shape('path',{d:'M65 25V280H610',stroke:'#334155',fill:'none'});shape('text',{x:300,y:330,'text-anchor':'middle',fill:'#123'},lab.xLabel);shape('text',{x:10,y:18,fill:'#123'},lab.yLabel);for(let i=0;i<=4;i++){const x=xmin+(xmax-xmin)*i/4,y=ymin+(ymax-ymin)*i/4;shape('text',{x:X(x),y:300,'text-anchor':'middle','font-size':12,fill:'#123'},x.toPrecision(3));shape('text',{x:58,y:Y(y)+4,'text-anchor':'end','font-size':12,fill:'#123'},y.toPrecision(3));}rows.forEach(r=>shape('circle',{cx:X(r.x),cy:Y(r.y),r:4,fill:'#176d9c'}));if(fit)shape('line',{x1:X(xmin),y1:Y(fit.m*xmin+fit.b),x2:X(xmax),y2:Y(fit.m*xmax+fit.b),stroke:'#b33','stroke-width':2});}
 if(lab.fit)button(controls,'Fit a straight line',()=>{const rows=notebook.rows;if(rows.length<3||new Set(rows.map(r=>r.x)).size<2){result.textContent='Record at least three readings at two or more x values.';return;}if(lab.parameters.some(p=>p.id!==lab.x&&new Set(rows.map(r=>r.params[p.id])).size>1)){result.textContent='Keep the other settings fixed within a data set before fitting a line.';return;}const x=rows.reduce((s,r)=>s+r.x,0)/rows.length,y=rows.reduce((s,r)=>s+r.y,0)/rows.length;const m=rows.reduce((s,r)=>s+(r.x-x)*(r.y-y),0)/rows.reduce((s,r)=>s+(r.x-x)**2,0),b=y-m*x;result.textContent=`Fitted line: y = ${m.toPrecision(4)}x + ${b.toPrecision(4)}. Compare it with your model and discuss the residual scatter.`;renderReadings({m,b});});
 const details=el('details','',area);el('summary','Model assumptions and limitations',details);el('p',lab.explanation,details);el('h2','3. Explain your findings',area);el('p',lab.reflection,area);const conclusion=el('textarea','',el('label','My conclusion, evidence and limitation',area));conclusion.maxLength=4000;conclusion.value=notebook.conclusion;conclusion.oninput=()=>{notebook.conclusion=conclusion.value;notebook.checked=false;save();};
 el('h2','4. Try a fresh check',area);el('p',lab.check.prompt,area);const answer=el('input','',el('label','Check answer',area));answer.value=notebook.check;answer.maxLength=100;answer.oninput=()=>{notebook.check=answer.value;notebook.checked=false;save();};const feedback=el('p',notebook.checked?'Fresh check completed. Written reasoning still needs your teacher’s review.':'',area);feedback.setAttribute('role','status');button(area,'Check my investigation answer',()=>{if(new Set(notebook.rows.map(r=>r.x)).size<3||notebook.conclusion.trim().length<20){feedback.textContent='First collect at least three different x values and write a conclusion using your readings.';return;}const checked=StudentPractice.check(lab.check,answer.value);feedback.textContent=checked.message+' '+(checked.correct?'Your written reasoning is not automatically marked.':lab.check.hint);if(checked.valid){const id=profile+':investigation:'+lab.id;StudentPractice.recordChoice(id,answer.value,checked.correct,!!StudentPractice.choiceDraft(id)?.assisted);notebook.checked=checked.correct;save();}});
 button(area,'Export this notebook',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({type:'studentdash-investigation',schema:1,profile,investigation:lab.id,notebook},null,2)],{type:'application/json'}));const a=el('a','',area);a.href=url;a.download=lab.id+'-notebook.json';a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);});renderReadings();}
 chooser.onchange=draw;const id=decodeURIComponent(location.hash.slice(1));if(labs.some(l=>l.id===id))chooser.value=id;draw();
})();
