/* Student home, topic history and revision planning. Profile content supplies every topic. */
(()=>{'use strict';
const root=document.querySelector('#student-centre');if(!root)return;
const context=JSON.parse(document.querySelector('#learning-context').textContent),catalog=window.PRACTICE_CATALOG,store=window.StudentLearningState;
const base=root.dataset.resourceBase||'',privateView=!!context.learner,scope=context.scope||catalog?.profile||'general';
const el=(tag,text,p)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;p?.append(e);return e;};
const btn=(p,text,fn)=>{const b=el('button',text,p);b.type='button';b.onclick=fn;return b;};
const link=(p,text,url)=>{const a=el('a',text,p);a.href=url;return a;};
const nodes=context.nodes||[],index=new Map(nodes.map(n=>[n.id,n]));
function parents(id){const ids=[],seen=new Set();while(index.has(id)&&!seen.has(id)){ids.push(id);seen.add(id);id=index.get(id).parent;}return ids;}
function questionNodes(q){const n=nodes.find(n=>n.code===q.topic);return n?parents(n.id):[];}
let state;let storageError='';try{state=store.read(scope);}catch(e){storageError='Browser saving is unavailable or the saved record needs review. Export before leaving.';state={schema:1,plans:{},notebooks:{},practice:null};}
function save(){try{store.save(scope,state);}catch(e){notice.textContent='Could not save in this browser. Export your learning record before leaving.';}}
const notice=el('p',storageError,root);notice.setAttribute('role','status');
const body=el('div','',root);body.tabIndex=-1;
function download(name,value){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=link(root,'Download',url);a.download=name;a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function file(p,label,handler){const l=el('label',label,p),input=el('input',undefined,l);input.type='file';input.accept='.json';input.onchange=async()=>{try{const f=input.files[0];if(!f)return;if(f.size>15*1024*1024)throw Error('Choose a file smaller than 15 MB.');handler(JSON.parse(await f.text()));}catch(e){notice.textContent=e.message;}finally{input.value='';}};}
function practice(){return privateView?state.practice:(window.StudentPractice?.snapshot()||state.practice);}
function events(){const rows=[...(context.events||[])],qs=new Map((catalog?.questions||[]).map(q=>[q.id,q]));for(const a of practice()?.attempts||[]){const q=qs.get(a.question);if(!q)continue;rows.push({id:a.id,source:q.kind==='investigation'?'Investigation check · self-reported':'Practice · self-reported',date:a.at,title:q.title,text:q.prompt,nodes:questionNodes(q),skills:(q.skills||[]).map(s=>catalog.skill_labels?.[s]||s),status:!a.correct?'Needs another attempt':a.assisted?'Completed with help or retry':'Correct independently',path:context.profile?context.profile+'/'+q.path:q.path});}return rows.sort((a,b)=>(b.date||'').localeCompare(a.date||'')||String(b.id).localeCompare(String(a.id)));}
function start(title){body.replaceChildren();const nav=el('div','',body);nav.className='lc-nav';btn(nav,'Home',home);btn(nav,'My progress',history);btn(nav,'Test preparation',planner);el('h1',title,body);}
function home(){body.replaceChildren();el('p',context.label||catalog?.label||'My learning',body).className='source';el('h1','What would you like to do today?',body);el('p','One step at a time. Choose a short activity, prepare for a test, or see how you are getting on.',body).className='welcome';const choices=el('div','',body);choices.className='choices';btn(choices,'Continue learning',learn);btn(choices,'Prepare for a test',planner);btn(choices,'See my progress',history);
 const upcoming=(context.exams||[]).filter(e=>e.date>=today()).sort((a,b)=>a.date.localeCompare(b.date))[0];if(upcoming)el('p','Next test: '+upcoming.title+' · '+upcoming.date,body);
 const details=el('details','',body);el('summary','Explore topics, investigations and tools',details);btn(details,'Choose a topic',learn);if(context.profile){link(el('p','',details),'Investigations',base+context.profile+'/investigations.html');link(el('p','',details),'Full practice library',base+context.profile+'/'+(catalog?.hub||'my-practice.html'));}
 const records=el('details','',body);el('summary','Save or restore my learning',records);btn(records,'Export learning record',()=>download('my-learning-record.json',{type:'studentdash-learning-record',schema:1,scope,record:state}));
 file(records,'Import learning record',raw=>{if(raw?.type!=='studentdash-learning-record'||raw.schema!==1||raw.scope!==scope)throw Error('This learning record belongs to another learner or collection.');const restored=store.validate(raw.record);state={...restored,plans:{...state.plans,...restored.plans},notebooks:{...state.notebooks,...restored.notebooks}};save();notice.textContent='Learning record restored. Imported matching plans and notebooks replace this browser’s versions.';});
 if(catalog)file(records,'Import my practice backup',raw=>{const progress=raw?.type==='studentdash-student-backup'?raw.progress:raw;state.practice=StudentPractice.validate(progress);save();notice.textContent='Practice snapshot attached to this learning page. Formal results are unchanged.';});
 if(context.profile)link(el('p','',records),'Combined practice backup',base+context.profile+'/student-backup.html');
 if(privateView){btn(records,'Clear saved learning on this page',()=>{if(confirm('Export first. Clear this page’s saved plan and imported practice? Formal results stay unchanged.')){state={schema:1,plans:{},notebooks:{},practice:null};save();home();}});el('p','Results last updated '+new Date(context.generated).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})+'. Imported practice remains separate from teacher records.',body).className='muted';}
}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function chooseNode(p,label='Topic'){const l=el('label',label,p),select=el('select','',l);select.setAttribute('aria-label',label);el('option','All topics',select).value='';nodes.forEach(n=>{el('option',(n.code?n.code+' · ':'')+n.label,select).value=n.id;});return select;}
function learn(){start('Choose your next step');const plans=(context.interventions||[]).filter(p=>p.date>=today());for(const plan of plans){const box=el('section','',body);box.className='panel';el('h2',plan.title,box);el('p',plan.instructions,box);el('p','Follow-up: '+plan.date,box);for(const r of context.resources||[])if(plan.nodes.includes(r.node_id)&&r.role===plan.role)link(el('p','',box),r.title,base+r.path);}
 const next=context.next;if(next?.focus){const box=el('section','',body);box.className='panel';el('h2','Suggested: '+next.focus.label,box);el('p',next.reason,box);for(const s of next.steps||[])if(s.path)link(el('p','',box),s.label,base+s.path);}
 const select=chooseNode(body,'Choose a topic to practise'),out=el('div','',body);function show(){out.replaceChildren();if(!select.value){el('p','Pick a topic to reveal its practice. You do not need to work through the whole question bank.',out);return;}const chosen=select.value;const qs=(catalog?.questions||[]).filter(q=>questionNodes(q).includes(chosen));if(qs.length){const recent=new Set((practice()?.attempts||[]).map(a=>a.question));const candidates=[...qs.filter(q=>!recent.has(q.id)),...qs.filter(q=>recent.has(q.id))];btn(out,'Show me five questions',()=>{const list=el('ol','',out);candidates.slice(0,5).forEach(q=>{const li=el('li','',list);link(li,q.prompt,base+(context.profile?context.profile+'/':'')+q.path);});});if(context.journal)link(el('p','',out),'Start a focused practice session',base+context.journal+'#topic='+encodeURIComponent(candidates[0].topic));}
 const resources=(context.resources||[]).filter(r=>parents(r.node_id).includes(chosen));for(const r of resources)link(el('p','',out),r.title,base+r.path);if(!qs.length&&!resources.length)el('p','No activity is mapped here yet. Try its parent topic or ask your teacher.',out);}
 select.onchange=show;show();}
function history(initial){start('Your learning history');el('p','Choose a topic or skill to see the evidence behind it. Sources stay separate; a successful practice answer does not change your test marks.',body);const select=chooseNode(body),skills=el('select','',el('label','Skill / classification',body));skills.setAttribute('aria-label','Skill / classification');el('option','All skills',skills).value='';[...new Set(events().flatMap(e=>e.skills||[]))].sort().forEach(s=>el('option',s,skills).value=s);if(initial&&index.has(initial))select.value=initial;const output=el('div','',body);
 function draw(){output.replaceChildren();const rows=events().filter(e=>(!select.value||e.nodes?.includes(select.value))&&(!skills.value||e.skills?.includes(skills.value)));el('p',`${rows.length} records.`,output);if(select.value)el('p','Whole-test feedback and exit tickets without reviewed topic links remain in All topics; they are not assigned to every topic in a test.',output);if(!rows.length){el('p','No mapped evidence yet. This does not mean you are behind.',output);return;}const last=rows.find(e=>e.score!==undefined&&e.score!==null);if(last)el('p','Latest scored evidence: '+last.source+' · '+last.date.slice(0,10)+'. Different tasks may have different difficulty; this is not a mastery score.',output);
 const list=el('ol','',output);list.className='timeline';rows.slice(0,150).forEach(e=>{const li=el('li','',list);el('p',e.source+' · '+(e.date||'Date not recorded').slice(0,10),li).className='source';el('h3',e.title,li);el('p',e.status+(e.score!==null&&e.score!==undefined?` · ${e.score}/${e.maximum}`:''),li);const d=el('details','',li);el('summary','Question and feedback',d);el('p',e.text,d);if(e.feedback)el('p',e.feedback,d);if(e.response)el('p','Your response: '+e.response,d);for(const task of e.tasks||[])el('p',task,d);for(const a of e.responses||[]){el('p',a.prompt,d);el('p','Your response: '+JSON.stringify(a.answer),d);if(a.feedback)el('p',a.feedback,d);}if(e.path)link(d,'Practise again',base+e.path);});if(rows.length>150)el('p','Showing the most recent 150 records. Narrow the topic or skill to see more focused history.',output);}
 select.onchange=draw;skills.onchange=draw;draw();}
function planner(){start('Prepare for a test');el('p','Choose the test, then set a realistic daily time. We suggest where to start from your recorded evidence; you can change the scope.',body);const exams=context.exams||[];const examLabel=el('label','Test',body),exam=el('select','',examLabel);exam.setAttribute('aria-label','Test');el('option','My own revision plan',exam).value='personal';for(const e of exams)el('option',e.title+' · '+e.date,exam).value=e.id;
 const controls=el('div','',body),result=el('div','',body);function setup(){controls.replaceChildren();result.replaceChildren();const id=exam.value,saved=state.plans[id],assigned=exams.find(e=>e.id===id);const title=el('input','',el('label','Plan title',controls));title.value=saved?.title||assigned?.title||'My revision';title.maxLength=160;const day=el('input','',el('label','Test date',controls));day.type='date';day.value=assigned?.date||saved?.date||today();day.min=today();if(assigned)day.readOnly=true;const minutes=el('input','',el('label','Minutes per day',controls));minutes.type='number';minutes.min=5;minutes.max=90;minutes.step=5;minutes.value=saved?.minutes||15;
 const scopeBox=el('details','',controls);el('summary','Choose the topics in this test',scopeBox);const selected=saved?.nodes||assigned?.nodes||[];nodes.forEach(n=>{const l=el('label','',scopeBox),c=el('input','',l);c.type='checkbox';c.value=n.id;c.checked=selected.includes(n.id);if(assigned&&!assigned.nodes.includes(n.id))return l.remove();l.append((n.code?n.code+' · ':'')+n.label);});if(assigned)el('p',assigned.instructions||'Teacher-selected test scope.',controls);
 btn(controls,'Build my revision plan',()=>{const chosen=[...scopeBox.querySelectorAll('input:checked')].map(c=>c.value),amount=Number(minutes.value);if(!chosen.length||!day.value||day.value<today()||!Number.isInteger(amount)||amount<5||amount>90){notice.textContent='Choose at least one topic, a date from today onwards, and 5–90 minutes per day.';return;}const plan={title:title.value.trim()||'My revision',date:day.value,minutes:amount,nodes:chosen,done:saved?.done||{}};state.plans[id]=plan;save();renderPlan(id,plan,result);});if(saved)renderPlan(id,saved,result);}
 exam.onchange=setup;setup();}
function renderPlan(id,plan,out){out.replaceChildren();const now=today();if(plan.date<now){el('p','This test date has passed. Choose a new date to make another plan.',out);return;}const days=Math.max(1,Math.ceil((Date.parse(plan.date+'T00:00:00Z')-Date.parse(now+'T00:00:00Z'))/86400000));const rows=events(),scoped=nodes.filter(n=>plan.nodes.some(id=>parents(n.id).includes(id)));const available=scoped.filter(n=>(context.resources||[]).some(r=>r.node_id===n.id)||(catalog?.questions||[]).some(q=>questionNodes(q).includes(n.id)));const candidates=available.length?available:scoped;
 // Prefer deepest mapped nodes so a parent and all its children do not become repeated tasks.
 const leaves=candidates.filter(n=>!candidates.some(m=>m.id!==n.id&&parents(m.id).includes(n.id)));
 const ranked=leaves.map(n=>{const evidence=rows.filter(e=>e.nodes?.includes(n.id)),formal=evidence.filter(e=>e.source==='Assessment'&&e.status==='graded'&&e.maximum&&e.score!==null);const lost=formal.reduce((t,e)=>t+e.maximum-e.score,0),latest=evidence[0];const old=latest&&Date.parse(latest.date)<Date.now()-30*86400000;const reason=lost?'Lost marks on a linked test question':!latest?'Not checked yet':old?'Evidence is over 30 days old':'Revisit and check independently';return {n,reason,priority:lost?0:!latest?1:old?2:3};}).sort((a,b)=>a.priority-b.priority||a.n.label.localeCompare(b.n.label));
 const capacity=Math.min(120,days*Math.max(1,Math.floor(plan.minutes/5))),tasks=ranked.flatMap(({n,reason})=>['basic','practice','check'].map(role=>({n,role,reason})));el('h2',plan.title,out);el('p',`${days} study day(s) · ${plan.minutes} minutes a day. Each activity is an estimated five-minute starting point; written work may take longer.`,out);if(tasks.length>capacity)el('p',`This budget fits ${capacity} of ${tasks.length} suggested steps. Increase the time, narrow the scope, or discuss priorities with your teacher.`,out);const perDay=Math.max(1,Math.floor(plan.minutes/5)),blocks=Math.ceil(Math.min(tasks.length,capacity)/perDay);const list=el('ol','',out);for(const [i,t]of tasks.slice(0,capacity).entries()){const key=t.n.id+':'+t.role,li=el('li','',list),l=el('label','',li),c=el('input','',l);c.type='checkbox';c.checked=!!plan.done[key];l.append(`Day ${blocks>1?Math.round(Math.floor(i/perDay)*(days-1)/(blocks-1))+1:1}: ${t.n.label} — ${t.role==='basic'?'Warm up':t.role==='practice'?'Practise':'Check without hints'}`);c.onchange=()=>{plan.done[key]=c.checked;state.plans[id]=plan;save();};el('p',t.reason,li);const r=(context.resources||[]).find(r=>r.node_id===t.n.id&&r.role===t.role);if(r)link(li,r.title,base+r.path);else{const q=(catalog?.questions||[]).find(q=>questionNodes(q).includes(t.n.id));if(q)link(li,'Open a related question',base+(context.profile?context.profile+'/':'')+q.path);else el('p','Use your class notes and ask your teacher for a suitable question.',li);}}
 if(!tasks.length)el('p','No mapped activities for that scope yet. Ask your teacher to link resources.',out);el('p','Ticking a step records your own completion, not demonstrated understanding.',out);btn(out,'Print this plan',()=>window.print());}
window.StudentCentre={home,learn,history,planner};document.querySelectorAll('[data-centre-action]').forEach(b=>b.onclick=()=>{document.getElementById('student-details')?.setAttribute('hidden','');({home,learn,history,planner}[b.dataset.centreAction]||home)();root.hidden=false;root.scrollIntoView();body.focus();});
if(document.getElementById('student-details')){document.getElementById('student-details').hidden=true;document.querySelectorAll('[data-section-link]').forEach(a=>a.addEventListener('click',()=>{document.getElementById('student-details').hidden=false;root.hidden=true;}));}
window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#learning-node='))history(decodeURIComponent(location.hash.slice(15)));});
home();if(location.hash.startsWith('#learning-node='))history(decodeURIComponent(location.hash.slice(15)));
})();
