"""Original skills practice; source references and classifications are profile data."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]/'resources'

def publish(profile,groups,source,scope):
 skills=[];questions=[]
 for group,page,rows in groups:
  for key,label,prompt,answer in rows:
   skills.append(dict(id=key,label=label,group=group,source_pages=[page]))
   questions.append(dict(id='skill-'+key,skills=[key],prompt=prompt,working=answer))
 assert len({s['id'] for s in skills})==len(skills)
 (ROOT/profile/'skills.json').write_text(json.dumps(dict(schema=1,source=source,scope=scope,skills=skills,questions=questions),ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
chem=[]
def C(group,page,rows):chem.append((group,page,rows))
C('Tool 1 · Safe measurement',34,[
('safety','Safety, ethics and environmental care','A school investigation proposes 500 cm³ of corrosive solution although 20 cm³ would suffice. What should change before starting? Include disposal and consent where relevant.','Use a teacher-approved microscale method, a risk assessment, specified protection and labelled waste collection. Follow local disposal procedures. Obtain informed consent if people or personal data are involved; avoid unnecessary harm.'),
('mass','Measure mass','A boat weighs 1.26 g empty and 3.74 g with sample. Calculate sample mass and describe checks before weighing.','2.48 g. Level and zero the balance, use a suitable check mass, avoid hot samples and record resolution and uncertainty.'),
('volume','Measure volume','Choose apparatus to transfer 25.00 cm³ for a titration and explain how to read and drain it.','Use a suitable volumetric pipette, conditioned with the solution, and a pipette filler. Read the meniscus at eye level and follow the drainage specification; a beaker is less precise.'),
('time','Measure elapsed time','Gas forms as soon as reagents touch. How would you time collection of 20 cm³ and reduce timing uncertainty?','Define and synchronize start and endpoint events. Repeat trials or use suitable video/data logging; document mixing delays and clock resolution.'),
('temperature','Measure temperature','Two probes read 24.1 and 26.8 °C in the same water. What should you check?','Check calibration against a reference, immersion, stirring, equilibration, resolution and response time. Avoid contact with the vessel wall.'),
('length','Measure length','A chromatography front is 5.2 cm from the origin and a spot centre is 3.1 cm from it. Explain the distance measurements and calculate Rf.','Measure along the solvent direction from the same origin to the front and spot centre. Rf = 3.1/5.2 ≈ 0.60, without units.'),
('ph','Measure pH','A probe just measured an alkaline sample. Prepare it to measure a weakly acidic sample reliably.','Calibrate using suitable buffers, rinse with deionized water, blot appropriately, immerse and wait for stability. Avoid contamination from the previous sample.'),
('current','Measure electric current','Draw how to measure current through an electrolytic cell and explain the initial meter-range choice.','Put the ammeter in series, not directly across the supply. Start on a suitable high range and refine it; record amperes and uncertainty.'),
('voltage','Measure potential difference','Draw a meter connection across two cell electrodes. Why should the instrument draw little current?','A high-resistance voltmeter goes in parallel. Small current reduces changes in cell conditions and internal-resistance voltage drop.')])
C('Tool 1 · Laboratory techniques',35,[
('standard','Prepare a standard solution','Plan preparation of 250.0 cm³ of 0.1000 mol dm⁻³ Na₂CO₃ using a dry primary standard, M = 106.0 g mol⁻¹. Calculate mass.','2.650 g. Dissolve, transfer quantitatively with washings into a volumetric flask, make up to the mark at its calibration temperature and mix thoroughly.'),
('dilution','Carry out a dilution','Make 100.0 cm³ of 0.0200 mol dm⁻³ solution from 0.100 mol dm⁻³ stock. Explain the apparatus and calculation.','c₁V₁ = c₂V₂ gives 20.0 cm³ stock. Transfer with appropriate volumetric apparatus, dilute to 100.0 cm³ and mix, following chemical-specific precautions.'),
('constant-mass','Dry to constant mass','Successive heat–cool–weigh results are 12.846, 12.801, 12.799 and 12.799 g. Which supports constant mass? Why cool?','The last two agree within resolution. Cool under specified dry conditions to reduce convection error and moisture uptake. Judge agreement against measurement uncertainty.'),
('distillation','Distillation and reflux','Sketch an arrangement to heat a reaction without losing volatile reactants, then a different arrangement to collect a volatile product.','Use vertical reflux to return condensate, then distillation to a receiver to collect a fraction. Keep heated apparatus vented as specified; never seal it.'),
('chromatography','Paper and thin-layer chromatography','A sample gives Rf values 0.25, 0.50, 0.80; a reference gives 0.50 under identical conditions. What follows?','At least three components are resolved; one is consistent with the reference. Matching Rf alone does not prove identity. Compare identical solvent, stationary phase and conditions.'),
('separation','Separate mixtures','Recover dry sand, salt crystals and collected water separately from sand, sodium chloride and water. Outline the sequence.','Filter, wash and dry sand. Distil the filtrate to collect water, then crystallize, separate and dry salt. Justify steps using solubility and volatility.'),
('calorimetry','Calorimetry','100 g of solution warms by 4.0 K; c = 4.18 J g⁻¹ K⁻¹. Estimate heat gained and propose a relevant improvement.','q = 1672 J ≈ 1.7 kJ. Use insulation and a lid; consider calorimeter heat capacity and remaining losses. State the heat-capacity and no-loss assumptions.'),
('titration','Acid–base and redox titration','Compare endpoints for acid–base and acidified permanganate titrations. Describe three practices that improve titre measurement.','Use an appropriate indicator or pH change for acid–base work; permanganate can supply a faint persistent colour endpoint. Condition apparatus, remove bubbles, read at eye level, add dropwise near endpoint and seek concordant titres.'),
('cells','Electrochemical cells','Sketch a zinc–copper galvanic cell with salt bridge and explain why removing the bridge stops sustained current.','Show Zn oxidation, Cu²⁺ reduction, external electron flow and bridge ion movement. Without ionic charge balance, charge buildup prevents sustained reaction.'),
('colorimetry','Colorimetry and spectrophotometry','A calibration gives A = 1200c with c in mol dm⁻³. Find c for A = 0.360 and explain blank and range checks.','c = 3.00 × 10⁻⁴ mol dm⁻³. A blank corrects background; consistent wavelength and cuvettes matter. Dilute unknowns outside the validated linear range.'),
('molecular-models','Physical and digital molecular models','Build or draw methane and ethene models. Compare a physical model with a digital representation and identify limitations.','Show tetrahedral methane and planar geometry around ethene carbons. Balls and sticks simplify electron distribution, motion, relative sizes and boundaries; models are representations.'),
('recrystallization','Recrystallization','A crude solid dissolves well hot but poorly cold. Plan purification and explain why too much solvent reduces recovery.','Dissolve in minimum hot solvent, remove insoluble impurities if necessary, cool, filter, wash with a little cold solvent and dry. Extra solvent retains more dissolved product.'),
('melting','Melting-point determination','A reference melts at 121–122 °C; a sample at 116–120 °C. Interpret this and improve the measurement.','A depressed broad range is consistent with impurity, not definitive identity evidence. Use a dry finely powdered sample, appropriate loading, calibration and slow heating near melting.')])
C('Tool 2 · Technology',35,[
('sensors','Collect data with sensors','Record cooling with a temperature sensor, or design the settings if unavailable. What acquisition and storage choices are necessary?','Calibrate, choose range and sampling interval for the response time, record units and time origin, and retain raw data with metadata. Actual data collection requires equipment.'),
('databases','Select and extract database evidence','Two databases report enthalpies at different temperatures and states. How would you select comparable data?','Match identity, state, temperature, pressure and units. Retain provenance, access/version information and uncertainty; do not combine incompatible entries without correction.'),
('simulation','Generate simulation data','Use the gas explorer to generate five pressure–volume pairs at fixed temperature and amount. How does the evidence differ from laboratory data?','Record settings and assumptions while varying one variable. Agreement with the implemented law demonstrates model behavior, not independent experimental validation.'),
('spreadsheet','Process data in spreadsheets','Enter 24.10, 24.20, 24.15 in cells. Calculate mean and range using formulas, then change 24.20 to 24.80. What updates?','Use AVERAGE and MAX minus MIN. Initially mean 24.15, range 0.10; afterward mean 24.35, range 0.70. Preserve original data and document changes.'),
('digital-graphs','Graph with technology','Plot time values 0, 10, 20, 30 s against gas volumes 0, 18, 31, 40 cm³ in a spreadsheet. Explain chart and axis choices.','Use an XY scatter chart with numeric time on x and volume on y, units, sensible scales and an appropriate curve. Avoid misleading category axes.'),
('computer-model','Computer modelling','Use T = 20 + 60exp(−0.1t) to generate temperatures at 0, 5, 10 minutes. State an assumption to test experimentally.','80, approximately 56.4 and 42.1 °C. Ambient temperature and cooling coefficient are assumed constant; compare measured residuals, not merely a smooth curve.')])
C('Tool 3 · Mathematical processing',35,[
('arithmetic','Arithmetic and algebra','A sample has mass 12.0 g and molar mass 40.0 g mol⁻¹. Rearrange m = nM and calculate n with units.','n = m/M = 0.300 mol. Division cancels grams and leaves moles.'),
('number-operations','Fractions, ratios, percentages and powers','A mixture is 3/8 solute by mass. Give decimal, percentage and solute:solvent ratio; evaluate the reciprocal of 2².','0.375; 37.5%; 3:5; 0.25. A solute:solvent ratio uses different quantities from the solute:total fraction.'),
('logarithms','Logarithmic calculations','Calculate −log₁₀(2.0 × 10⁻³). What happens if the argument increases tenfold?','Approximately 2.699. The logarithm increases by 1, so its negative decreases by 1.'),
('exponentials','Exponential calculations · AHL','AHL: c(t) = 0.50exp(−0.20t). Find c(5) and the fraction remaining.','c(5) ≈ 0.184; fraction remaining ≈ 0.368. Match the coefficient and time units.'),
('rates','Rates from tables','Concentration falls from 0.80 to 0.62 mol dm⁻³ between 10 and 40 s. Find the positive average disappearance rate.','(0.80−0.62)/(40−10) = 0.0060 mol dm⁻³ s⁻¹. This is an interval average.'),
('mean-range','Mean and range','For 18.2, 18.6, 18.4, calculate mean and range. Does a small range establish accuracy?','Mean 18.4; range 0.4. Closely grouped results can share a systematic offset.'),
('scientific-notation','Scientific notation','Write 0.000450 in scientific notation and multiply by 2.0 × 10³.','4.50 × 10⁻⁴; product 0.90 to two significant figures.'),
('estimate','Approximation and estimation','Estimate 19.8 × 4.1, then calculate it. Is 811.8 plausible?','Estimate about 80; exact product 81.18. A result near 812 has a factor-of-ten error.'),
('negligible','Justify neglecting small effects','A process releases about 2000 J. A correction is below 1 J, with measurement uncertainty ±50 J. Is neglecting it defensible?','Yes at this precision because it is small compared with uncertainty. State the assumption and revisit it if the precision target changes.'),
('order','Orders of magnitude','Compare 6 × 10⁴ with 3 × 10⁷. Give their ratio and its nearest power of ten on a logarithmic scale.','The larger divided by the smaller is 500. Its nearest power of ten on a logarithmic scale is 10³.')])
C('Tool 3 · Quantities and uncertainty',36,[
('proportionality','Proportionality and correlation','When x doubles, y halves. Propose a model. Compare with a direct proportional relationship, and explain why positive or negative correlation alone does not establish proportionality.','y = k/x is consistent if xy stays constant. In direct proportionality y = kx, y also doubles and y/x stays constant. Correlation alone does not establish either formula or causation.'),
('percentage-change','Percentage change and difference','A reading rises from 40 to 50. Calculate percentage change relative to 40 and percentage difference relative to the mean.','25% change; 10/45 × 100 ≈ 22.2% difference. State the denominator convention.'),
('error','Percentage error and uncertainty','An observation is 9.6 ± 0.2; accepted value 10.0. Calculate percentage error and percentage uncertainty.','Absolute percentage error 4.0%; percentage uncertainty about 2.1%. Error compares with a reference; uncertainty describes an assigned range.'),
('variables-type','Continuous and discrete variables','Classify reaction time and number of bubbles counted. Why is rounded time still continuous?','Time is continuous; a bubble count is discrete. Rounding limits recorded resolution, not the underlying variable type.'),
('units','SI units and prefixes','Convert 25.0 cm³ to dm³ and m³, and 3.20 kJ to J.','0.0250 dm³; 2.50 × 10⁻⁵ m³; 3200 J. Volume conversions cube length factors.'),
('symbols','Scientific symbols and booklet notation','Distinguish n, N, Nₐ and M in n = m/M and N = nNₐ, with units.','n: amount, mol; N: particle count; Nₐ: Avogadro constant, mol⁻¹; M: molar mass, for example g mol⁻¹. Check units in each equation.'),
('precision','Significant figures and decimal places','Report 12.347 g with uncertainty 0.2 g. Explain the rounding.','(12.3 ± 0.2) g. Value and uncertainty end at the same decimal place.'),
('raw-uncertainty','Raw and processed uncertainty','Each ruler reading has uncertainty ±1 mm. Why can a distance found by subtracting two readings have greater uncertainty?','Both endpoints contribute. Maximum absolute uncertainties add for a difference; distinguish this convention from a statistical uncertainty estimate.'),
('uncertainty-range','Record uncertainty intervals','Give the interval for (20.0 ± 0.2) cm³ and explain the recorded precision.','19.8–20.2 cm³. Value and uncertainty use the same decimal place.'),
('propagation','Propagate uncertainties','Using maximum-uncertainty rules, find uncertainty in (10.0 ± 0.2) − (4.0 ± 0.1) and percentage uncertainty in their product. AHL: what about the first quantity squared?','Difference 6.0 ± 0.3; product percentage uncertainty 2.0% + 2.5% = 4.5%. Squaring gives about 4.0% for the first quantity. These are maximum-uncertainty approximations.'),
('uncertainty-forms','Absolute, relative and percentage uncertainty','For 50.0 ± 0.5, give fractional and percentage uncertainty and convert back.','Fractional 0.010; percentage 1.0%; 0.010 × 50.0 recovers absolute uncertainty 0.5.'),
('r-squared','Coefficient of determination','Fits to the same response data give R² = 0.91 and 0.99. Does the latter prove a valid physical model?','No. Check residual patterns, assumptions, complexity and independent predictions; a high R² alone does not establish physical validity.')])
C('Tool 3 · Graphs',36,[
('sketch','Sketch qualitative graphs','Sketch concentration against time for a reactant consumed quickly initially and then more slowly. Label unscaled axes.','A decreasing curve becoming less steep; label time and concentration. A straight line would imply a constant rate.'),
('charts','Choose tables and graph types','Choose displays for category counts, a continuous length distribution and paired concentration–time observations.','Bar chart; histogram with suitable class widths; scatter/line graph. Raw-data tables require units and appropriate precision.'),
('plot','Plot linear and nonlinear relationships','Plot (1,1), (2,4), (3,9), (4,16). Explain why joining only first and last with a line is misleading.','The points follow y = x² with increasing slope. Plot every point on labelled numeric scales and use a justified curve.'),
('best-fit','Lines and curves of best fit','Sketch a best-fit line for (1,2.1), (2,3.9), (3,6.2), (4,7.8). Must it pass through every point or the origin?','A line near y = 2x is reasonable. It represents the overall pattern; forcing the origin needs scientific justification.'),
('graph-features','Gradients, intercepts, extrema and area','A rate–time graph joins (0,0), (2,6), (4,0). Time is seconds and rate mol s⁻¹. State maximum rate, initial gradient, intercept and area.','6 mol s⁻¹ at 2 s; initial gradient 3 mol s⁻²; initial intercept zero; area 12 mol.'),
('error-bars','Uncertainty bars','Draw (1,4.0 ± 0.5) and (2,4.4 ± 0.5). Do overlapping bars prove equal true values?','Intervals 3.5–4.5 and 3.9–4.9 overlap, but overlap does not prove equality or replace an appropriate comparison.'),
('interpolation','Interpolation and extrapolation','A calibration spans concentrations 0.10–0.50. Compare predictions at 0.30 and 0.80.','0.30 is interpolation; 0.80 is extrapolation and needs validation or dilution into the calibrated range.')])
C('Inquiry 1 · Exploring',36,[
('initiative','Independent ideas and initiative','Propose two investigable questions about an approved cooling experiment. Choose one and justify your own decision.','Specify measurable quantities, compare alternatives and explain your interest, for example how an approved insulation material changes a fitted cooling rate.'),
('sources','Consult and select relevant sources','Compare a manufacturer specification, peer-reviewed method and unattributed social-media claim for planning pH measurements.','Use specifications for instrument limits and a relevant method for procedure and validation. Check expertise, evidence, date and applicability; corroborate claims and cite sources.'),
('research-question','Research questions and hypotheses','Replace “Does temperature matter?” with a measurable reaction-rate research question and a testable hypothesis.','Specify system, approved temperature range, controlled concentration and rate measure. Predict a relationship with scientific reasoning; distinguish question from hypothesis.')])
C('Inquiry 1 · Design and control',37,[
('prediction','Explain scientific predictions','Predict the effect of increasing exposed surface area of the same solid mass on initial rate with excess solution. Give a reason and a control.','More exposed reactive sites can increase initial rate under surface-controlled conditions. Control temperature and solution concentration.'),
('creative-design','Creative investigation design','Design a fair comparison of three approved insulating materials and a clear presentation of results.','Use repeat cooling runs with controlled starting conditions and a justified order. Show labelled cooling curves or fitted rates with uncertainties; explain design choices.'),
('investigation-types','Laboratory, database, simulation and modelling approaches','Outline four approaches to investigating a gas law: laboratory, database, simulation and mathematical modelling. Compare their evidence.','Laboratory data are measurements; databases provide prior observations with provenance; simulations explore programmed assumptions; models generate predictions. Simulated agreement is not independent experimental evidence.'),
('variable-selection','Choose and justify variables','In a concentration–rate experiment, identify independent, dependent and three control variables.','Vary concentration, measure a defined rate, control temperature, total volume and apparatus/mixing. Explain how each affects the outcome.'),
('sampling-design','Range and number of measurements','Improve a design with only two temperatures and no repeats, within an approved safe range.','Use several distributed values and repeats to reveal curvature and estimate variability. Pilot the range; justify quantity against time and precision.'),
('method','Valid reproducible methodology','Outline a reproducible dissolution-time comparison at two temperatures and identify a confounder.','Specify mass, particle size, solvent volume, stirring, temperature control and endpoint. Changing particle size with temperature would confound effects.'),
('pilot','Pilot and refine methods','A pilot finishes before the stopwatch starts reliably. What could you change and test again?','Use an approved slower condition or faster acquisition. Recheck measurable range, mixing delay, repeatability and sensor response while preserving the research question.'),
('calibration','Calibrate apparatus','A probe reads 1.5 °C at a reliable 0 °C reference and 51.5 °C at 50 °C. Propose a correction and limitation.','Subtract 1.5 °C within the validated range if stable. Two points do not establish all-range linearity or remove other uncertainty.'),
('environment','Control environmental conditions','A cell-voltage experiment runs by a sunny window for three hours. What could vary and how would you control it?','Control and record temperature; consider evaporation and concentration changes. Use a suitable monitored environment.'),
('insulation','Limit unwanted heat transfer','Explain how a lid and insulation improve calorimetry and identify remaining limitations.','They reduce heat exchange and evaporation. Calorimeter heat capacity, incomplete reaction, probe delay and remaining heat loss can still matter.')])
C('Inquiry 2 · Collect and interpret',37,[
('qualitative','Record qualitative observations','Replace “the reaction was amazing” with useful observations for a fictional gas-forming reaction that produces a white solid.','Describe bubbles, white precipitate and sequence/timing of changes. Separate observations from inferred chemical explanations.'),
('quantitative','Collect sufficient quantitative data','Design a raw-data table for three reaction-time repeats at five concentrations. What belongs in headings?','Concentration and time with units, replicate identifiers and instrument uncertainty; record controlled conditions and consistent precision. Retain original readings.'),
('collection-issues','Address data-collection problems','A gas syringe sticks during a run. What should be recorded and done with the trial?','Document the event and affected readings, correct the apparatus safely and repeat as justified. Keep raw records and explain exclusions.'),
('processing','Accurate data processing','Gas volume rises from 12 to 42 cm³ between 10 and 30 s. Calculate average rate and explain why 42/30 differs.','(42−12)/(30−10) = 1.5 cm³ s⁻¹. 42/30 assumes zero volume at time zero and a different averaging interval.'),
('interpretation','Interpret qualitative and quantitative evidence','Colour changes while absorbance falls from 0.80 to 0.40. Under a validated linear calibration, what follows and what is assumed?','Absorbing-species concentration approximately halves if wavelength, path length and response stay constant. Colour alone is qualitative; other absorbers may interfere.'),
('diagrams','Interpret diagrams and charts','Two particle drawings show six pairs and three clusters of four. What information is needed before claiming a reaction occurred?','Identify symbols, whether clusters mean bonds or proximity, and whether equal material amounts are shown. Drawing arrangement alone does not establish chemical change.'),
('patterns','Explain patterns and relationships','At fixed temperature, pressure–volume pairs are (100,4), (200,2), (400,1). Describe and justify a relationship.','pV = 400 for each: inverse proportionality, consistent with a fixed amount of approximately ideal gas.'),
('outliers','Justify outlier decisions','Times are 30.1, 30.4, 30.2, 45.8 s. Is distance from the others enough reason to delete the last?','No. Investigate a documented procedural issue, retain raw data and compare conclusions with/without it. Do not delete solely to improve agreement.'),
('quality','Accuracy, precision, reliability and validity','Three readings cluster near 11.0; the reliable reference is 10.0. Discuss the four quality concepts.','They may be precise but inaccurate. Reliability concerns consistency on repetition; validity concerns whether the method measures the intended quantity and supports the question.')])
C('Inquiry 3 · Conclusions and evaluation',37,[
('conclusion','Justify conclusions from data','Rates are 2.0 ± 0.2 and 4.1 ± 0.3 under two conditions. Write a bounded conclusion.','The second is roughly twice the first under these conditions. Two points alone cannot establish a rate law over all concentrations.'),
('scientific-context','Compare with accepted context','Your enthalpy is −45 ± 5 kJ mol⁻¹; a comparable accepted value is −57. Discuss.','The reference is outside −50 to −40. Examine assumptions, losses, conditions and reference uncertainty; do not conceal disagreement.'),
('question-conclusion','Answer the research question','A temperature–rate study concludes only that the solution changed colour. Improve the conclusion structure.','State the rate–temperature relationship, cite processed data and uncertainty, delimit the investigated range and use colour only as supporting evidence.'),
('uncertain-conclusions','Uncertainty in conclusions','Values are 5.0 ± 1.0 and 5.4 ± 1.0. Is a strong difference claim justified?','The difference is small relative to uncertainty. These intervals alone do not support a strong claim; use appropriate analysis and improve precision where feasible.'),
('hypothesis-evaluation','Evaluate hypotheses','A linear-increase hypothesis produces repeatable data that curve and flatten. What next?','Describe deviations, check uncertainty and validity, and revise or reject linearity in the tested range rather than dismissing contrary evidence.'),
('errors','Random and systematic error','Compare variable stopwatch reaction delay with a balance always 0.20 g too high. How do repeats and calibration help?','Repeats can reduce random variation in a mean; a systematic offset needs calibration/correction. Repetition alone does not remove bias.'),
('limitations','Limitations and assumptions','Calorimetry assumes the heat capacity of water. How could this affect q and how would you investigate?','q is proportional to assumed c. Overestimated c overestimates heat magnitude. Obtain reliable data for the actual solution or measure c; separate this from heat-loss effects.')])
C('Inquiry 3 · Improvements',38,[('improvements','Realistic methodological improvements','Replace “use better equipment” with two specific improvements for a cooling investigation.','Use a faster calibrated sensor for lag and a controlled monitored environment for ambient drift. Link each change to its limitation and explain remaining uncertainty.')])
C('Scientific thinking and learning',12,[
('models','Scientific models and limits','An ideal-gas simulation matches pV = nRT exactly. Does it validate the law near real-gas liquefaction?','No. Real measurements are needed; attractions and molecular volume matter. Agreement with programmed assumptions is not independent validation.'),
('evidence','Evidence and falsifiability','What observation would challenge “all colourless solutions are neutral”, and how would you obtain it safely?','A calibrated pH far from neutral in an approved colourless sample challenges the universal claim. Appearance alone cannot establish pH.'),
('research-integrity','Research integrity and collaboration','A partner proposes removing awkward data and copying another group’s graph without credit. Respond.','Retain original data, investigate anomalies transparently, analyse honestly and acknowledge sources and contributions. Discuss ideas without presenting others’ work as your own.'),
('planning','Plan and reflect on learning','Plan 20 minutes to improve uncertainty propagation and identify when to seek help.','Allocate time to an example, an independent attempt and comparison. Record the error type, choose a matched follow-up and seek targeted help if the method remains unclear.')])
C('Scientific thinking · Explanations',13,[
('theories','Hypotheses, theories and laws','Explain the difference between a law describing a gas relationship and a theory explaining it. Describe how a failed prediction should be investigated.','A law describes a regular relationship; a theory supplies an explanatory framework that generates predictions. Check conditions and evidence, then revise or reject claims where justified. A supported theory does not simply become a law.')])
C('Scientific thinking · Society',14,[
('peer-review','Peer review and shared science','A new catalyst claim is published with no method or raw data. What should reviewers request, and does peer review guarantee correctness?','Request reproducible methods, original data, uncertainty, controls and transparent analysis. Independent scrutiny and replication strengthen confidence; peer review is not an infallible guarantee.'),
('global-impact','Global and ethical impacts of science','A new industrial process saves energy but creates a difficult waste stream. Outline a decision that considers environmental, social and economic effects and how to communicate uncertainty to the public.','Compare whole-process energy, waste hazards, exposure, benefits, costs and distribution of impacts. Consult affected groups, consider alternatives and unexpected consequences, and communicate evidence and uncertainty honestly.')])
C('Approaches to learning · Thinking',21,[
('atl-thinking','Thinking and transfer','Connect gas-particle ideas with reaction rates to invent a linking question. State a hypothesis, propose evidence, defend an ethical boundary, and describe how you would change your learning strategy after an unsuccessful attempt.','For example ask how temperature changes the fraction of collisions able to react. Give a scientific prediction and controlled safe method, evaluate the evidence rather than the desired result, and reflect on which representation or worked example helps transfer the ideas.')])
C('Approaches to learning · Communication and collaboration',22,[
('atl-communication','Communication and audience','Explain a calorimetry result to a younger student and to a chemistry class, using one diagram and a short digital slide. Ask a partner to restate your claim, then give constructive feedback on relevance, structure and notation.','Adapt terminology and detail to each audience, label quantities and units, separate evidence from explanation and use an accurate diagram. Listen actively, check understanding, and give specific respectful feedback that improves the argument.'),
('atl-social','Social skills and teamwork','Plan roles for a group investigation, accounting for different strengths and needs. Describe how to resolve a disagreement about an outlier, invite another perspective, and review your own and peers’ contributions respectfully.','Agree roles and a common goal, seek each person’s evidence, apply a justified data policy rather than majority preference, and document decisions. Use specific constructive feedback and consider how your words affect others.'),
('atl-research','Research, citation and validation','Find two contrasting accounts of a chemical process using a library catalogue and a search engine. Describe search terms, evaluate bias and relevance, cross-check a numerical claim and cite both in one consistent style.','Use specific terms and traceable sources, check authorship, evidence, conditions and dates, compare like-for-like quantities, acknowledge ideas fully and distinguish primary evidence from commentary.'),
('atl-self-management','Self-management and feedback','Break a report into stages with deadlines. Set a learning goal, plan distraction-free work, explain how to handle a setback, and revise one paragraph after feedback.','Use realistic milestones for research, analysis, drafting and review. Track progress, seek targeted feedback, revise the goal when evidence warrants, and treat setbacks as information for improving the plan.')])
C('Assessment skills',28,[
('knowledge','Scientific knowledge and terminology','Distinguish an atom, molecule and ion, then give one example of each without treating all molecules as compounds.','An atom is a unit of an element; a molecule is a discrete bonded group of atoms; an ion has net charge. Examples: He, O₂ and Na⁺. O₂ is a molecule of an element, not a compound.'),
('apply-knowledge','Apply scientific concepts and methods','A 0.10 mol sample is diluted from 0.20 to 0.50 dm³ without loss of solute. Find both concentrations and explain what stays constant.','Concentrations are 0.50 and 0.20 mol dm⁻³. Solute amount remains 0.10 mol; concentration changes because volume changes.'),
('evaluate-science','Analyse, evaluate and synthesize evidence','Two groups report different reaction rates, but one used warmer solutions and a different gas syringe. Explain why their results cannot isolate the syringe effect and propose a comparison.','Temperature and apparatus are confounded. Compare syringes at the same controlled temperature and concentration with repeats, inspect calibration and uncertainty, and retain both data sets with their conditions.'),
('ethical-investigation','Conduct an ethical scientific investigation','Plan a teacher-approved cooling-water investigation, including safe temperature limits, controls, repeats, raw records and disposal. If equipment and supervision are available, collect data and evaluate your plan; otherwise record what remains untested.','Obtain the approved method and limits, define a measurable question, control relevant conditions, collect labelled repeated data safely and analyse uncertainty. Retain raw evidence, report limitations honestly and distinguish a written plan from demonstrated practical performance.')])
publish('ib-chemistry',chem,'https://anatolia.edu.gr/images/highschool/IBDP/Chemistry%20Guide%202025.pdf','Tools and inquiry skills, guide PDF pp. 34–38, plus nature of science and approaches-to-learning categories. AHL tasks are labelled. Written questions prepare for practical work; performance requires practical observation.')
math=[]
def M(group,page,rows):math.append((group,page,rows))
M('Prior learning · Number and algebra',29,[
('number-sets','Number systems','Classify −3, 0.25 and √2 as integer, rational or irrational, and explain which are real.','−3 is integer and rational; 0.25 = 1/4 is rational; √2 is irrational. All are real.'),
('units','SI and derived units','Convert 72 km h⁻¹ to m s⁻¹ and explain why area conversion differs from length conversion.','20 m s⁻¹. Area conversion squares the length factor; volume conversion cubes it.'),
('rounding','Rounding and approximation','Round 0.004786 to two significant figures and state the rounding interval for 7.3 to the nearest tenth.','0.0048; interval 7.25 ≤ x < 7.35 under the usual half-up positive-number convention.'),
('absolute','Absolute value','Evaluate |−7| and solve |x| = 4. Explain the distance interpretation.','7; x = ±4. Absolute value is distance from zero.'),
('arithmetic','Arithmetic and order of operations','Evaluate −3 + 2(5 − 1) and 3/4 ÷ 2/5, showing order of operations.','5 and 15/8 = 1.875. Evaluate brackets before multiplying; division by a fraction multiplies by its reciprocal.'),
('primes','Primes, factors and multiples','List prime factors of 84 and give three positive multiples of 12.','84 = 2² × 3 × 7; examples 12, 24, 36. Distinguish factors from multiples.'),
('proportion','Ratio, percentage and proportion','Split 80 in ratio 3:5, then increase the larger share by 15%.','Shares 30 and 50; increased share 57.5. The ratio has eight total parts.'),
('algebra','Expand and factor expressions','Expand 3(x+4) and factor x²+5x+6. Check by expansion.','3x+12 and (x+2)(x+3). Expanding the factors recovers the original polynomial.'),
('rearrange','Rearrange formulae','Make h the subject of V = πr²h and identify a restriction on r.','h = V/(πr²), with r ≠ 0; for a physical cylinder r > 0.'),
('substitute','Substitute into expressions','Evaluate 2x²−3y for x=−2, y=5, showing the substituted expression.','2(−2)²−3(5) = 8−15 = −7. Square the signed input in brackets.'),
('powers','Positive integer exponents','Evaluate 2³ × 2⁴ and explain the exponent rule.','2⁷ = 128. Multiplying powers of the same base adds exponents.'),
('inequalities','Inequalities and intervals','Solve −2x < 6 and show the answer on a number line.','x > −3; reverse the inequality when dividing by a negative. Draw an open endpoint at −3 and shade right.'),
('surds','Simplify roots','Simplify √72 and check its approximate value on a calculator.','6√2 ≈ 8.485. Extract the square factor 36.'),
('standard-form','Standard form','Write 5 600 000 and 0.00056 in standard form.','5.6 × 10⁶ and 5.6 × 10⁻⁴; coefficient between 1 and 10.'),
('currency','Currency notation and conversion','At a fictional rate of 1 EUR = 11.5 NOK, convert EUR 80 into NOK. What else might affect an actual transaction?','NOK 920 before fees. Real transactions may use different buy/sell rates and charges; the stated fictional rate fixes this calculation.'),
('linear','Linear equations','Solve 3x+7=22 and verify by substitution.','x=5; 3(5)+7=22.'),
('systems','Systems of linear equations','Solve x+y=9 and 2x−y=3. Verify the solution in both equations.','Adding gives 3x=12, so x=4 and y=5. Both original equations hold.'),
('sets','Set notation, union and intersection','For A={1,2,3} and B={3,4}, find A∪B and A∩B. Explain membership notation.','Union {1,2,3,4}; intersection {3}. For example 2∈A but 2∉B.'),
('graphing','Graph linear and quadratic functions with technology','Graph y=2x+1 and y=x² on your calculator or graphing software. Find intersections and record the window used.','Solve x²=2x+1: x=1±√2, with corresponding y=3±2√2. Use a window displaying both intersections and verify algebraically.'),
('representations','Mappings, tables and graphs','For f(x)=2x+1 on inputs −1,0,1, give ordered pairs, a table and plotted points.','Pairs (−1,−1),(0,1),(1,3); use identical input–output relationships in all representations. The specified domain has three points, not all real inputs.')])
M('Prior learning · Geometry',30,[
('pythagoras','Pythagoras and its converse','A triangle has sides 6,8,10. Is it right-angled? Explain the converse test.','6²+8²=10², so the angle opposite side 10 is right.'),
('coordinates','Midpoint and distance','Find midpoint and distance between (−1,2) and (5,10).','Midpoint (2,6); distance √(6²+8²)=10.'),
('geometry-language','Points, lines, planes and angles','Describe the difference between a point, line and plane, then identify two intersecting lines in a drawn plane.','A point represents a position, a line extends in two directions, and a plane is a flat two-dimensional surface. Label the intersection and an angle between the lines.'),
('angles','Degrees and compass directions','A turn goes clockwise from north to southwest. State the angle and explain how it differs from an anticlockwise turn to the same direction.','Clockwise 225°; anticlockwise 135°. The direction of measurement matters.'),
('triangle-angles','Triangle angle sum','Two interior angles are 48° and 67°. Find the third and show your reasoning.','180−48−67=65° for a Euclidean triangle.'),
('trigonometry','Right-triangle trigonometry','A 5 m ladder makes a 60° angle with the ground. Find vertical height and state the calculator angle mode.','5sin60° ≈ 4.33 m, using degree mode.'),
('bearings','Three-figure bearings','B is northeast of A. Give its three-figure bearing and the reverse bearing.','045° and 225°, measured clockwise from north.'),
('transformations','Geometric transformations','Transform (2,1) by translation (3,−2), reflection in the y-axis, 90° anticlockwise rotation about the origin and enlargement of scale 2 from the origin. Treat each separately.','(5,−1), (−2,1), (−1,2), (4,2). Specify the centre, axis or vector for each transformation.'),
('circles','Circle vocabulary and measures','Draw a circle with radius 3 and label diameter, chord, tangent, arc, sector and segment. Calculate area and circumference.','Diameter 6, area 9π, circumference 6π. A sector is bounded by two radii and an arc; a segment by a chord and arc; a tangent touches at one point.'),
('plane-shapes','Plane figures and compound area','An 8 by 5 rectangle has a 2 by 2 square removed from one corner. Find area and perimeter; compare the defining properties of rectangles, squares, rhombuses, kites and trapezoids.','Area 36; perimeter remains 26 for this corner removal. Rectangles have four right angles; squares also have four equal sides; rhombuses have four equal sides; kites have two pairs of adjacent equal sides. State the convention for trapezoids (one pair of parallel sides, or at least one pair).'),
('solids','Recognize three-dimensional shapes','Describe how to distinguish a prism, pyramid, sphere, cylinder and cone. Sketch and label one feature of each.','Prisms have matching parallel end faces; pyramids taper from a polygon to an apex; spheres have points equidistant from a centre; cylinders have circular ends; cones taper from a circular base.'),
('volume-area','Volumes and surface areas','A closed cuboid has dimensions 2,3,4. Find volume and surface area. Find the volume of a triangular prism with base triangle area 6 and length 5, and a cylinder of radius 2 and height 3. Explain how to handle joined solids.','Cuboid volume 24 and area 52; prism volume 30; cylinder volume 12π. Add non-overlapping volumes for joined solids and exclude internal shared faces from exposed surface area.')])
M('Prior learning · Data and probability',30,[
('data-displays','Collect and display data','Collect ten fictional travel times and choose a bar chart, pie chart, pictogram or line graph for a clearly stated purpose. Explain when each is suitable.','Categories suit bars, composition can suit pies, pictograms require a key, and ordered time series suit line graphs. Record units and avoid treating arbitrary category order as time.'),
('summary','Mean, median, mode and range','Find mean, median, mode and range of 2,3,3,4,8.','Mean 4, median 3, mode 3, range 6.'),
('probability','Simple probability','A bag has three red and five blue counters. Find the probability of one red draw and its complement.','3/8 and 5/8; these complementary probabilities sum to 1.'),
('venn','Venn diagrams','In a group of 30, 18 study A, 14 study B and 8 study both. Draw a Venn diagram and find how many study neither.','A only 10, both 8, B only 6, neither 6.'),
('trees','Tree diagrams','Draw a tree for two independent fair-coin tosses and calculate exactly one head.','Four equally likely paths HH, HT, TH, TT; probability 2/4=1/2. Multiply along branches and add the relevant paths.'),
('speed','Speed, distance and time','A cyclist travels 18 km in 45 minutes. Find average speed in km h⁻¹ and explain why this need not be instantaneous speed.','18/0.75=24 km h⁻¹. An average over the journey can conceal changing speed.')])
M('Mathematical inquiry and assessment skills',26,[
('knowledge','Select mathematical facts and techniques','A rectangular field has fixed perimeter. Which mathematical facts help find the greatest possible area, and why?','Use perimeter and area formulae, express area in one variable and locate the maximum of a quadratic or use an equivalent justified argument.'),
('problem-solving','Solve abstract and contextual problems','A taxi charges a fixed 4 plus 2.5 per kilometre. With a budget of 29, what is the maximum distance? State assumptions.','Solve 4+2.5d≤29 to get d≤10 km. Assume the stated continuous fare, no extra charges and a nonnegative distance.'),
('communication','Communicate and interpret mathematics','Rewrite “the answer is 12” as a mathematical conclusion for a model predicting 12 litres after three minutes. Include notation, units and a limitation.','For example V(3)=12 L under the stated model. Define V and time units, identify the domain and avoid claiming exact real-world measurement from a model prediction.'),
('technology','Use technology appropriately','Use graphing technology to solve x³−x−1=0, then check the reported root by substitution and explain a display limitation.','The real root is approximately 1.324718. A graph can suggest a root but a poor window can hide features; numerical output needs substitution and sensible precision.'),
('reasoning','Construct a mathematical argument','Prove that the sum of any two consecutive integers is odd. Is checking five examples enough?','Let the integers be n and n+1. Their sum is 2n+1, odd for every integer n. Examples suggest but do not prove a universal result.'),
('inquiry','Conjecture, test and justify','Investigate sums of the first n odd positive integers for n=1 to 5. Conjecture a rule, test a new case and explain with a diagram or argument.','Sums 1,4,9,16,25 suggest n². Test n=6 gives 36; adding the next odd number creates a new border of a square, supporting the general rule.')])
M('Modelling cycle',20,[
('model-question','Define a modelling problem','Turn “bus delays are bad” into a mathematical modelling question, defining an outcome and data needed.','For example predict journey time from departure time over a specified route. Define units, population and response, collect relevant observations and distinguish prediction from causal explanation.'),
('model-assumptions','State assumptions and simplify','A tank model assumes a constant inflow and no outflow. Name two real features ignored and explain when that simplification is defensible.','Changing pump rate and leaks are ignored. The model may suit a short controlled interval if their effects are small relative to the required accuracy.'),
('model-choice','Choose model and domain','A population cannot grow beyond a finite habitat capacity. Explain why an unlimited exponential model may fit early data but need a restricted domain.','Early growth can approximate a constant percentage rate; resource limits later violate that assumption. Specify a tested time range and consider a bounded model for longer-term predictions.'),
('model-parameters','Determine model parameters','A line passes through (0,3) and (4,11). Determine parameters and interpret them if x is hours and y litres.','y=2x+3. Initial amount 3 L; modeled increase 2 L per hour.'),
('model-validation','Validate with residuals and new data','A model predicts 8,10,12 for observed 7,10,15. Calculate residuals and propose a validation step.','Observed minus predicted: −1,0,3. Plot residuals and test on data not used to fit; systematic patterns suggest a missing feature.'),
('model-refine','Refine a model','Residuals from a line form a U-shaped pattern. Suggest a refinement and explain how to avoid assuming complexity always improves the model.','Consider a quadratic or scientifically justified alternative, compare residuals and independent prediction error, and balance fit against complexity and assumptions.'),
('model-context','Interpret predictions in context','A model estimates 2.7 buses needed for a trip. What decision should be reported and why?','Under a capacity requirement of at least 2.7 buses, provide 3 whole buses. Explain integer feasibility and the model assumptions rather than reporting an impossible fractional allocation.'),
('model-transfer','Transfer and evaluate a model','A fare model fitted in one city is used in another. What must be checked before transferring it?','Check fare rules, rates, units, fees, domain and data comparability. Refit or reject it if the context changes relevant assumptions.')])
M('Technology toolkit',21,[
('tech-patterns','Use technology to explore patterns','Use a spreadsheet to generate n and n² for n=1 to 10, then first differences. Explain the pattern and test n=11.','Squares have consecutive odd first differences; the next difference is 21. The spreadsheet supports exploration; an argument is needed for a general proof.'),
('tech-representations','Connect representations with technology','Display y=(x−2)²+1 as a formula, table and graph. Show how the vertex appears in all three.','Vertex (2,1); the squared term is zero at x=2, the table has its lowest listed value there and the graph has a turning point. Explain table-domain limitations.'),
('tech-data','Organize and analyse data digitally','Enter 4,5,5,6,10 in a spreadsheet and obtain mean and median using formulas. Change 10 to 30 and compare.','Initial mean 6, median 5; new mean 10, median 5. Record formulas and explain sensitivity to an extreme observation.'),
('tech-simulation','Use simulations','Simulate 100 fair-coin tosses, record the proportion of heads and repeat. Must each run have exactly 50 heads?','No. Record random variation and compare proportions across runs. The theoretical probability is 0.5; simulation frequency fluctuates.'),
('tech-geometry','Use dynamic geometry','Construct a triangle and its angle bisectors with dynamic geometry software. Drag a vertex and state a conjecture about their intersection.','The internal angle bisectors meet at the incenter, equidistant from the sides. A dynamic construction suggests the relationship but is not alone a proof.'),
('tech-calculus','Numerical calculus with technology','Use technology to evaluate the area under y=x² from 0 to 2, then verify by integration.','The integral is 8/3 ≈ 2.6667. Set bounds and function correctly; compare with the antiderivative x³/3.'),
('tech-statistics','Statistical distributions and tests with technology','Use a calculator to find P(X≤2) for X~Bin(10,0.3). Explain cumulative versus point probability.','Approximately 0.3828. Cumulative adds probabilities for 0,1,2; P(X=2) alone is about 0.2335. Record the distribution and parameters, not only the output.')])
M('Toolkit · Research, collaboration and reflection',23,[
('research','Research and source evaluation','Find two sources for a fictional city population model. What metadata would you record and what would make sources incompatible?','Record source, date, geographic definition, measurement method and units. Different boundaries or years may prevent direct comparison; cite sources and assess reliability.'),
('collaboration','Collaborate with clear authorship','In a practice modelling project, assign roles for collecting, checking and explaining data. How should contributions and disagreements be recorded?','Agree responsibilities and checkpoints, keep a contribution log and resolve disagreements using evidence. Discuss ideas while keeping individual assessed work and authorship clear.'),
('self-management','Plan and monitor work','Plan three short sessions for a modelling investigation, including checkpoints and a response to missing data.','Separate question/data planning, analysis and evaluation/communication. Set achievable outputs, record progress and revise the scope or obtain justified replacement evidence.'),
('reflection','Reflect critically','A fitted curve looks impressive but predicts a negative population outside the data range. Write a reflection that changes what you would report.','Restrict the domain, explain why extrapolation is invalid, consider a more appropriate model and test it. Reflection should affect the analysis or conclusion, not just say the task was interesting.'),
('presentation','Present and cite mathematical work','Outline a short exploration report with a clear aim, methods, results and reflection. Where should graphs and citations appear?','Use a coherent sequence, define symbols, integrate labelled graphs near their discussion and cite data/methods where used. State personal decisions, limitations and conclusions without copying another report.')])
publish('ib-math-ai-sl',math,'https://dp.uwcea.org/docs/Mathematics%20-%20Applications%20and%20Interpretation%20Subject%20Guide.pdf','AI SL prior learning, mathematical inquiry, modelling, technology and toolkit skills. HL-only prior-learning extensions are outside this SL collection. Subject-specific methods remain linked to the 39 syllabus sections. Technology and collaboration tasks require the stated tool or partner; written comparison is not proof of performance.')
