"""Authored AI SL section questions: four skill families with five related variants."""
from math import pi, sqrt
from mcq_authoring import Bank


def math_questions():
    b = Bank()
    N, T = b.numeric, b.text
    for i in range(1, 6):
        a, d, n = i + 2, i + 1, i + 5
        N('1.1', f'Evaluate {a}.5 × 10^{i+2}.', (a+.5)*10**(i+2), 'Multiply the coefficient by the stated power of ten.')
        N('1.1', f'Evaluate ({a} × 10^4) × (2 × 10^-2).', a*200, 'Multiply coefficients and add exponents: the power is 10².')
        N('1.1', f'Evaluate ({2*a} × 10^6) ÷ (2 × 10^3).', a*1000, 'Divide coefficients and subtract exponents.')
        T('1.1', f'Which is the normalized standard form of {a*10000}?', f'{a} × 10^4', [f'{a} × 10^3', f'{a} × 10^5', f'{a*10} × 10^4'], 'In a × 10ⁿ, the coefficient must satisfy 1 ≤ a < 10, and the value must be unchanged.')
        N('1.2', f'An arithmetic sequence has first term {a} and common difference {d}. Find term {n}.', a+(n-1)*d, 'Use uₙ = u₁ + (n−1)d.', [a+n*d, a*n, a+d])
        N('1.2', f'Find the sum of the first {n} terms of the arithmetic sequence with u₁ = {a} and d = {d}.', n*(2*a+(n-1)*d)/2, 'Use Sₙ = n[2u₁ + (n−1)d]/2.')
        N('1.2', f'Terms 3 and 8 of an arithmetic sequence are {a+2*d} and {a+7*d}. Find d.', d, 'There are five equal increments between terms 3 and 8; divide their difference by 5.')
        N('1.2', f'An arithmetic sequence has u₅ = {a+4*d} and d = {d}. Find u₁.', a, 'Subtract four common differences from the fifth term.')
        N('1.3', f'A geometric sequence has u₁ = {a} and ratio 2. Find u_{i+3}.', a*2**(i+2), 'Use uₙ = u₁rⁿ⁻¹.')
        N('1.3', f'Find the sum of the first {i+3} terms of {a}, {2*a}, {4*a}, … .', a*(2**(i+3)-1), 'Use Sₙ = u₁(rⁿ−1)/(r−1).')
        N('1.3', f'A geometric sequence has consecutive terms {3*a} and {9*a}. Find its common ratio.', 3, f'Divide the later term {9*a} by the preceding term {3*a}.', [a, 6*a, 1/3])
        N('1.3', f'A population starts at {100*a} and halves each day. What does the model predict after {i} days?', 100*a*.5**i, 'Multiply the initial value by (1/2) to the number of elapsed days.')
        N('1.4', f'{1000*a} is invested at {d}% annually, compounded annually. Find its value after 3 years.', 1000*a*(1+d/100)**3, 'Use FV = PV(1+r)³ with r as a decimal.')
        N('1.4', f'A machine worth {2000*a} depreciates by 10% each year. Find its value after {i+1} years.', 2000*a*.9**(i+1), 'Each year retains 90% of the preceding value.')
        N('1.4', f'An investment grows by {i+5}% in one year while prices rise by 2%. Find the percentage real growth.', ((1+(i+5)/100)/1.02-1)*100, 'Divide the investment growth factor by the price growth factor, then subtract 1 and multiply by 100.')
        N('1.4', f'{1000*a} earns 6% nominal annual interest compounded monthly for one year. Find its final value.', 1000*a*(1+.06/12)**12, 'The monthly rate is 0.06/12 and there are 12 compounding periods.')
        N('1.5', f'Find log₁₀({10**i}).', i, 'A logarithm is the exponent: 10 raised to this value equals the argument.')
        N('1.5', f'Solve 2^x = {2**(i+2)}.', i+2, 'Match powers of the same base, or divide logarithms.')
        N('1.5', f'Evaluate {a}^-2.', a**-2, 'A negative exponent gives a reciprocal: a⁻² = 1/a².')
        N('1.5', f'Solve 3 × 2^t = {3*2**(i+3)}.', i+3, 'Divide by 3, then take the base-two logarithm.')
        N('1.6', f'A length is reported as {10+i} cm to the nearest cm. What is its lower bound, in cm?', 10+i-.5, 'The rounding interval extends half a unit below and above the reported value.')
        N('1.6', f'The exact value is {50+10*i}; an estimate is {55+10*i}. Find the absolute percentage error.', 500/(50+10*i), 'Absolute percentage error is |estimate−exact|/|exact| × 100.')
        N('1.6', f'Round {12340+100*i} to three significant figures.', round((12340+100*i)/100)*100, 'Keep the first three significant digits and use the next digit to decide whether to round up.')
        N('1.6', f'A rectangle has length {10+i} cm and width {5+i} cm, each to the nearest cm. Find the upper bound for its area in cm².', (10+i+.5)*(5+i+.5), 'For positive dimensions, multiply the two upper bounds.')
        N('1.7', f'A loan balance is {1000*a}. Monthly interest is 1%, then a payment of {100*d} is made. Find the new balance.', 1000*a*1.01-100*d, 'Apply interest before subtracting the end-of-month payment.')
        N('1.7', f'A savings account receives {100*a} at the end of each year for 3 years, at 5% annual interest. Find the balance just after the third deposit.', 100*a*(1+1.05+1.05**2), 'The first deposit earns two years of interest, the second one year and the third none.')
        N('1.7', f'What equal annual payment repays a loan of {1000*a} in 2 years at 10% annual interest, with payments at year-end?', 1000*a*1.1**2/2.1, 'After two payments the balance is PV(1.1)² − A(1.1+1) = 0.')
        N('1.7', f'A deposit of {100*a} is made at the beginning of each of 2 years at 4% annual interest. Find the balance at the end of the second year.', 100*a*(1.04**2+1.04), 'Beginning-of-year deposits earn two years and one year of interest respectively.')
        N('1.8', f'Solve x + y = {a+d} and x − y = {a-d}. Find x.', a, 'Add the equations to eliminate y, then divide by 2.')
        N('1.8', f'If x = {a}, solve 2x + 3y = {2*a+3*d} for y.', d, 'Substitute x, subtract 2x, and divide by 3.')
        T('1.8', f'Which pair gives the roots of x² − {a+d}x + {a*d} = 0?', f'{d} and {a}', [f'{-d} and {-a}', f'0 and {a+d}', f'{a*d} and {a+d}'], f'The expression factors as (x−{d})(x−{a}).')
        N('1.8', f'A system has x+y+z={a+d+2}, x−y={a-d}, and z=2. Find y.', d, 'Substitute z=2, then subtract the second equation from x+y to get 2y.')
        N('2.1', f'Find the gradient through (1, {a}) and (4, {a+3*d}).', d, 'Gradient is the change in y divided by the change in x.')
        N('2.1', f'A line has gradient {d} and passes through (2, {2*d+a}). Find its y-intercept.', a, 'Use c = y−mx in y=mx+c.')
        N('2.1', f'Find the gradient of a line perpendicular to y = {d}x + {a}.', -1/d, 'Non-vertical perpendicular gradients have product −1.')
        N('2.1', f'Where does y = {d}x − {d*a} cross the x-axis? Give the x-coordinate.', a, 'Set y=0 and solve the linear equation.')
        N('2.2', f'For f(x) = {d}x + {a}, find f({i+1}).', d*(i+1)+a, 'Substitute the input for x.')
        N('2.2', f'For f(x) = {d}x + {a}, find f⁻¹({d*4+a}).', 4, 'Undo addition of a, then divide by the multiplier d.')
        N('2.2', f'For f(x) = √(x−{a}), what is the smallest real x in the domain?', a, 'The radicand must be non-negative.')
        T('2.2', f'What is the range of f(x) = (x−{i})² + {a}, for real x?', f'y ≥ {a}', [f'y ≤ {a}', 'All real y', f'y > {a}'], 'A square is at least zero and attains zero at the vertex.')
        N('2.3', f'f(x)={d}x and g(x)=x+{a}. Find (f+g)(2).', 2*d+2+a, 'Evaluate both functions at 2 and add the outputs.')
        N('2.3', f'f(x)=x² and g(x)=x+{a}. Find f(g(2)).', (2+a)**2, 'Apply g first, then square its output.')
        N('2.3', f'f(x)=x²+{i} and g(x)=2x. Find (f−g)(3).', 9+i-6, 'Subtract g(3) from f(3).')
        N('2.3', f'f(x)={a}x and g(x)=x−1. Find (fg)(3), where fg means the product.', 6*a, 'Multiply f(3)=3a by g(3)=2; this is not composition.')
        N('2.4', f'Find the x-coordinate of the vertex of y=(x−{a})²+{i}.', a, 'The squared term is zero at the vertex.')
        N('2.4', f'Find the positive x-intercept of y=x²−{a*a}.', a, 'Set y=0 and take the positive square root.')
        N('2.4', f'Find the x-coordinate where y=2x+{a} and y=x+{a+d} intersect.', d, 'Equate the expressions for y and solve for x.')
        N('2.4', f'For y={a}/(x−{d}), what is the x-coordinate of the vertical asymptote?', d, 'The denominator is zero at the vertical asymptote.')
        N('2.5', f'A taxi costs {a} plus {d} per kilometre. Find the cost of a 6 km trip.', a+6*d, 'Add the fixed charge to distance times the variable charge.')
        N('2.5', f'A population model is P(t)={100*a}(1.2)^t. Find P(2).', 100*a*1.2**2, 'Apply the growth factor twice.')
        N('2.5', f'A height model is h(t)=−t²+{2*a}t+{i}. Find its maximum height.', a*a+i, f'The vertex occurs at t={a}; substitute this into h(t).')
        N('2.5', f'A periodic model is y={a} sin(30t°)+{10+i}. What is its amplitude?', a, 'Amplitude is the absolute value of the coefficient of sine.')
        N('2.6', f'A model predicts {20+i} but the observation is {24+i}. Find the residual (observed minus predicted).', 4, 'Residual = observed − predicted.', [-4,44+2*i,0])
        N('2.6', f'A model y={d}x+{a} is fitted using x-values from 0 to 10. What does it predict at x=5?', 5*d+a, 'Substitute into the fitted equation; 5 is within the observed interval.')
        T('2.6', f'A model was fitted for ages 10–{20+i}. Predicting for age {30+i} is an example of what?', 'Extrapolation', ['Interpolation', 'Random sampling', 'An exact observation'], 'The prediction is outside the range used to fit the model and may be unreliable.')
        N('2.6', f'A proposed model has residuals {i}, {-i}, {i+1} and {-i-1}. Find the sum of squared residuals.', 2*i*i+2*(i+1)**2, 'Square every residual before adding; opposite signs do not cancel squared errors.')
        N('3.1', f'Find the volume of a cylinder of radius {i+1} cm and height {a} cm, in cm³.', pi*(i+1)**2*a, 'Use V=πr²h.')
        N('3.1', f'Find the volume of a sphere of radius {i+1} cm, in cm³.', 4*pi*(i+1)**3/3, 'Use V=4πr³/3.')
        N('3.1', f'Find the diagonal length of a cuboid with sides {i}, {2*i} and {2*i} cm.', 3*i, 'Use the three-dimensional Pythagorean theorem: √(a²+b²+c²).')
        N('3.1', f'Find the total surface area of a cube of side {a} cm, in cm².', 6*a*a, 'A cube has six equal square faces.')
        N('3.2', f'A right triangle has hypotenuse {2*a} cm and an angle of 30°. Find the side opposite that angle, in cm.', a, 'Opposite = hypotenuse × sin 30°.')
        N('3.2', f'Two sides are {a} and {a+1} cm with included angle 60°. Find the third side, in cm.', sqrt(a*a+(a+1)**2-a*(a+1)), 'Use c²=a²+b²−2ab cos C.')
        N('3.2', f'A triangle has sides {a} and {2*a} cm with included angle 30°. Find its area in cm².', a*a/2, 'Use area = ab sin C/2.')
        N('3.2', f'In a triangle, a side of length {a} cm is opposite 30°. Find the side opposite 60°, in cm.', a*sqrt(3), 'Use the sine rule: b/sin60° = a/sin30°.')
        N('3.3', f'The bearing of B from A is {20+10*i}°. Find the bearing of A from B in degrees.', 200+10*i, 'Reverse a bearing by adding 180° and reducing modulo 360°.')
        N('3.3', f'A person walks {2*a} km on a bearing of 30°. Find the eastward displacement in km.', a, 'Eastward displacement is distance × sin(bearing).')
        N('3.3', f'A tower is {10*a} m away horizontally. Its top has elevation 45°. Ignoring eye height, find its height in m.', 10*a, 'Height = horizontal distance × tan45°.')
        N('3.3', f'A ship sails {a} km north and then {a} km east. Find its straight-line distance from the start in km.', a*sqrt(2), 'The displacements are perpendicular, so apply Pythagoras.')
        N('3.4', f'A sector has radius {a} cm and angle 60°. Find its arc length in cm.', pi*a/3, 'Arc length = (θ/360) × 2πr.')
        N('3.4', f'A sector has radius {a} cm and angle 90°. Find its area in cm².', pi*a*a/4, 'Sector area = (θ/360) × πr².')
        N('3.4', f'A sector has radius {a} cm and angle 180°. Find its perimeter in cm.', pi*a+2*a, 'Add the arc length and the two radii; arc length alone is not the perimeter.')
        N('3.4', f'An arc is {a}π cm long on a circle of radius {2*a} cm. Find its angle in degrees.', 90, 'The arc is one quarter of the circumference, so its angle is 90°.', [45,180,360])
        N('3.5', f'Find the x-coordinate of the midpoint of ({i},2) and ({i+6},8).', i+3, 'Average the endpoint x-coordinates.')
        N('3.5', f'A segment has gradient {a}. Find the gradient of its perpendicular bisector.', -1/a, 'The perpendicular gradient is the negative reciprocal.')
        N('3.5', f'The perpendicular bisector of the segment from ({i},0) to ({i+8},0) has equation x=k. Find k.', i+4, 'A horizontal segment has a vertical perpendicular bisector through its midpoint.')
        N('3.5', f'A segment joins (0,0) and ({2*a},{2*a}). Its perpendicular bisector is y=−x+c. Find c.', 2*a, f'The midpoint is ({a},{a}); substitute it into y=−x+c.')
        N('3.6', f'Two sites are at (0,0) and ({2*a},0). On their Voronoi boundary, x=k. Find k.', a, 'The boundary is the perpendicular bisector of the segment joining the sites.')
        T('3.6', f'Sites A=(0,0), B=({4*a},0), C=(0,{4*a}). Which is nearest to P=({a},0)?', 'A', ['B', 'C', 'All three equally'], 'Distances to A and B are a and 3a; the distance to C is √17a, so A is nearest.')
        N('3.6', f'On a horizontal road, sites are at x=0, x={2*a}, and x={6*a}. Find the length of the middle site’s Voronoi interval.', 3*a, f'Boundaries are at x={a} and x={4*a}; subtract to find the interval length.')
        T('3.6', f'Sites are A=(0,0) and B=({2*a},0). A point P=({a},{i}) lies where?', 'On the boundary between their regions', ['Strictly inside A’s region', 'Strictly inside B’s region', 'At site A'], 'Its x-coordinate is the midpoint; its distances to A and B are equal.')
        N('4.1', f'A survey samples {20*i} people from a population of {200*i}. What percentage is sampled?', 10, 'Sample percentage = sample size/population size × 100.', [.1,20,90])
        N('4.1', f'A population of 1000 includes {100*i} members of group A. A proportional stratified sample has size 80. How many should come from A?', 8*i, 'Allocate sample places in the same proportion as the population.')
        T('4.1', f'A school surveys only the first {10+i} volunteers who respond online. What is a key concern?', 'Volunteer bias', ['The sample must be a census', 'All students had equal probability of selection', 'A larger population removes all bias'], 'Willingness to respond may be related to the topic; a volunteer sample need not be representative.')
        N('4.1', f'A list has {100*i} people. A systematic sample of {10*i} is needed. What sampling interval should be used after a random start?', 10, 'Divide population size by sample size.', [i,100,5])
        N('4.2', f'The first three class frequencies are {i+2}, {i+3} and {i+4}. Find the cumulative frequency through class 3.', 3*i+9, 'Add the frequencies up to and including the third class.')
        N('4.2', f'A histogram class has width {i+1} and frequency {5*(i+1)}. Find its frequency density.', 5, 'Frequency density = frequency/class width.', [5*(i+1),i+1,1/5])
        N('4.2', f'A distribution has Q₁={10+i} and Q₃={22+i}. Find its interquartile range.', 12, 'IQR = Q₃−Q₁.', [16+i,32+2*i,6])
        N('4.2', f'A box plot has Q₁={i} and Q₃={i+8}. Find the upper outlier fence using 1.5×IQR.', i+20, 'Upper fence = Q₃ + 1.5(Q₃−Q₁).')
        N('4.3', f'Find the mean of {i}, {i+3}, {i+6}.', i+3, 'Add all observations and divide by 3.')
        N('4.3', f'Find the median of {i}, {i+1}, {i+4}, {i+7}.', i+2.5, 'For four ordered observations, average the middle two.')
        N('4.3', f'A data set has mean {10+i}. Each value is transformed to 3x+2. Find the new mean.', 3*(10+i)+2, 'The mean undergoes the same linear transformation.')
        N('4.3', f'A data set has standard deviation {i+1}. Each value is transformed to 2x+7. Find the new standard deviation.', 2*(i+1), 'Multiply standard deviation by |2|; adding 7 does not change spread.')
        N('4.4', f'A regression line is y={i+1}x+{a}. Predict y at x=5.', 5*(i+1)+a, 'Substitute into the fitted regression equation.')
        N('4.4', f'A regression predicts {15+i} for an observed value of {18+i}. Find the residual.', 3, 'Residual is observed minus predicted.', [-3,33+2*i,0])
        T('4.4', f'A sample has Pearson correlation r=−0.{i+4}. What does the negative sign indicate?', 'Higher x tends to accompany lower y', ['Every point lies on a straight line', 'x causes y to decrease', 'The y-values must all be negative'], 'The sign gives the direction of the linear association, not causation or the signs of individual values.')
        N('4.4', f'A model predicts y={i+2}x+10. What change in predicted y follows an increase of 4 in x?', 4*(i+2), 'Multiply the gradient by the change in x.')
        N('4.5', f'A bag contains {i+2} red and {i+3} blue counters. Find P(red) on one random draw.', (i+2)/(2*i+5), 'Divide favourable outcomes by the total number of counters.')
        N('4.5', f'An event has probability {i}/10. In 200 independent trials, what is its expected frequency?', 20*i, 'Expected frequency = number of trials × event probability.')
        N('4.5', f'P(A)={i}/10. Find P(not A).', 1-i/10, 'Complementary probabilities sum to 1.')
        N('4.5', f'In {100*i} trials an event occurs {30*i} times. Find its relative frequency.', .3, 'Divide the occurrence count by the total number of trials.', [3,.7,30])
        N('4.6', f'P(A)=0.5, P(B)={i}/10 and P(A∩B)={i}/20. Find P(A∪B).', .5+i/20, 'Use P(A∪B)=P(A)+P(B)−P(A∩B).')
        N('4.6', f'A bag has {i+2} red and {i+3} blue counters. A red is removed without replacement. Find the probability the next counter is red.', (i+1)/(2*i+4), 'Both the red count and the total decrease by one.')
        N('4.6', f'P(A∩B)={i}/20 and P(B)=0.5. Find P(A|B).', i/10, 'Conditional probability is P(A∩B)/P(B).')
        N('4.6', f'Independent events have P(A)=0.4 and P(B)={i}/10. Find P(A∩B).', .04*i, 'For independent events, multiply the probabilities.')
        N('4.7', f'X equals {10*i} with probability 0.2, otherwise 0. Find E(X).', 2*i, 'Multiply each value by its probability and sum.')
        N('4.7', f'A game pays {10*i} with probability 0.3, otherwise 0. Entry costs {i}. Find expected net gain.', 2*i, 'Expected payout is 3i; subtract the entry cost i.')
        N('4.7', f'X takes values 0, {i} and {2*i} with probabilities 0.2, 0.5 and 0.3. Find E(X).', 1.1*i, 'Use E(X)=Σxp(x).')
        N('4.7', f'A distribution assigns probabilities 0.2, {i}/10 and k to three outcomes. Find k.', .8-i/10, 'The probabilities of all possible outcomes must sum to 1.')
        N('4.8', f'X~Bin({10*i},0.3). Find its mean.', 3*i, 'The binomial mean is np.')
        N('4.8', f'X~Bin({i+2},0.5). Find P(X=0).', .5**(i+2), 'Zero successes means all trials fail: (1−p)ⁿ.')
        N('4.8', f'X~Bin({i+3},0.2). Find P(X=1).', (i+3)*.2*.8**(i+2), 'Use P(X=1)=n p (1−p)ⁿ⁻¹.')
        N('4.8', f'X~Bin({10*i},0.4). Find its variance.', 2.4*i, 'The binomial variance is np(1−p).')
        N('4.9', f'A normal distribution has mean {50+i} and standard deviation 5. Find the z-score of {60+i}.', 2, 'Use z=(x−μ)/σ.', [10,.4,-2])
        N('4.9', f'X is normal with mean {20+i} and standard deviation 3. Find P(X < {20+i}).', .5, 'A normal distribution is symmetric about its mean.', [.1587,.8413,1])
        N('4.9', f'A normal variable has mean {30+i} and standard deviation 4. The 97.5th percentile has z≈1.96. Find this percentile.', 30+i+1.96*4, 'Transform back using x=μ+zσ.')
        N('4.9', f'X is normal with mean {10+i} and standard deviation 2. Using P(−1<Z<1)≈0.6827, find P({8+i}<X<{12+i}).', .6827, 'The endpoints are one standard deviation below and above the mean.', [.3173,.9545,.5])
        N('4.10', f'Tied observations occupy ranks {i+1} and {i+2}. What rank should each receive?', i+1.5, 'Assign each tied observation the mean of the ranks it occupies.')
        N('4.10', f'Three tied observations occupy ranks {i+1}, {i+2}, {i+3}. What rank should each receive?', i+2, 'Average the three occupied ranks.')
        T('4.10', f'For {i+4} distinct paired observations, the y-ranks exactly match the x-ranks. What is Spearman’s correlation?', '1', ['−1', '0', 'It cannot be calculated from ranks'], 'Identical rank order gives perfect positive rank correlation.')
        T('4.10', f'For {i+4} distinct paired observations, the y-ranks are exactly the reverse of the x-ranks. What is Spearman’s correlation?', '−1', ['1', '0', 'It equals the sample size'], 'Reversed ranks give perfect negative rank correlation.')
        T('4.11', f'A test gives p=0.0{i} at significance level 0.10. What is the decision?', 'Reject the null hypothesis', ['Fail to reject the null hypothesis', 'Accept that the null is certainly true', 'The p-value is the probability the null is true'], 'Each stated p-value is below 0.10. Reject H₀ at this significance level; this does not prove the alternative.')
        N('4.11', f'An independence table has row total {10*i}, column total 20 and grand total 100. Find the expected count in that cell.', 2*i, 'Under independence, expected count = row total × column total / grand total.')
        N('4.11', f'Find the degrees of freedom for a chi-square independence test with {i+1} rows and 3 columns.', 2*i, 'Use (number of rows−1)(number of columns−1).')
        T('4.11', f'Two independent groups, with sample sizes {20+i} and {25+i}, are compared using a two-sided t-test of population means. Which null hypothesis is appropriate?', 'The two population means are equal', ['The two sample means must be equal', 'Every observation in the groups is identical', 'The population standard deviations must be zero'], 'The null concerns the population means, not equality of observed sample means.')
        N('5.1', f'For f(x)=x², find the average rate of change from x={i} to x={i+2}.', 2*i+2, 'Use [f(b)−f(a)]/(b−a).')
        N('5.1', f'For f(x)={a}x², what is the limiting gradient of secants at x=1?', 2*a, 'The limiting secant gradient is f′(1); differentiating gives f′(x)=2ax.')
        N('5.1', f'A distance changes from {10*i} m at t=2 s to {10*i+24} m at t=8 s. Find the average speed over this interval in m s⁻¹.', 4, 'Divide the change in distance, 24 m, by the elapsed time, 6 s.', [24,6,3])
        N('5.1', f'f(x)=x². Find [f({i}+0.1)−f({i})]/0.1.', 2*i+.1, 'Expand (x+h)²−x² and divide by h to obtain 2x+h.')
        T('5.2', f'f′(x)=2x−{2*i}. On which interval is f increasing?', f'x > {i}', [f'x < {i}', 'All real x', 'No real x'], 'A differentiable function increases where its derivative is positive.')
        T('5.2', f'f′(x)={2*i}−2x. On which interval is f decreasing?', f'x > {i}', [f'x < {i}', 'All real x', 'No real x'], 'The derivative is negative when x exceeds the stated threshold.')
        N('5.2', f'f′(x)=3x−{i}. Find the derivative at x=2.', 6-i, 'Substitute x=2 into the derivative; the positive result indicates increasing behavior there.')
        T('5.2', f'f′(x)=−(x−{i})². What is true for x≠{i}?', 'f is decreasing', ['f is increasing', 'f is constant', 'f is undefined'], 'A nonzero square is positive, so its negative is strictly negative.')
        N('5.3', f'f(x)={a}x³. Find f′(2).', 12*a, 'Differentiate to get 3ax², then substitute x=2.')
        N('5.3', f'f(x)={a}x^-1. Find f′(1).', -a, 'The power rule gives −ax⁻².')
        N('5.3', f'f(x)={a}x²+{d}x+7. Find f′(1).', 2*a+d, 'Differentiate each term; the constant contributes zero.')
        N('5.3', f'f(x)=x⁴−{i}x². Find f′(2).', 32-4*i, 'Differentiate to 4x³−2ix and evaluate at 2.')
        N('5.4', f'Find the tangent gradient to y=x² at x={i}.', 2*i, 'The tangent gradient is y′=2x at the given x-coordinate.')
        N('5.4', f'Find the normal gradient to y={a}x² at x=1.', -1/(2*a), 'The tangent gradient is 2a; take its negative reciprocal.')
        N('5.4', f'The tangent to y=x² at x={i} is y={2*i}x+c. Find c.', -i*i, 'The line passes through (i,i²); substitute to solve for c.')
        N('5.4', f'The normal to y=x² at x={i} has gradient −1/{2*i}. Find its y-intercept.', i*i+.5, 'Use c=y−mx with the point (i,i²).')
        N('5.5', f'Evaluate ∫ from 0 to {i} of 2x dx.', i*i, 'An antiderivative is x²; evaluate at the two endpoints.')
        N('5.5', f'F′(x)=2x and F(0)={a}. Find F(3).', 9+a, 'Integrate to F=x²+C; the initial value gives C=a.')
        N('5.5', f'Evaluate ∫ from 1 to 3 of {a} dx.', 2*a, 'The integral of a constant is the rectangle area: height a times width 2.')
        N('5.5', f'Evaluate ∫ from 0 to 2 of {a}x² dx.', 8*a/3, 'An antiderivative is ax³/3.')
        N('5.6', f'f(x)=x²−{2*i}x+3. Find the x-coordinate of its stationary point.', i, 'Set f′(x)=2x−2i equal to zero.')
        T('5.6', f'f′ changes from negative to positive at x={i}. What type of stationary point is there?', 'Local minimum', ['Local maximum', 'Horizontal inflection point', 'Vertical asymptote'], 'The function changes from decreasing to increasing.')
        T('5.6', f'f′ changes from positive to negative at x={i+2}. What type of stationary point is there?', 'Local maximum', ['Local minimum', 'Horizontal inflection point', 'Vertical asymptote'], 'The function changes from increasing to decreasing.')
        N('5.6', f'For f(x)=(x−{i})²+{a}, find the minimum value of f.', a, 'The square has minimum zero, attained at x=i.')
        N('5.7', f'A rectangle has perimeter {8*a} m. Find the side length of the maximum-area rectangle, in m.', 2*a, 'For fixed perimeter, the maximum-area rectangle is a square; divide the perimeter by 4.')
        N('5.7', f'A rectangle is fenced on three sides against a wall using {12*a} m of fence. Find the optimal width perpendicular to the wall.', 3*a, 'With 2w+l=12a, area is w(12a−2w); set its derivative 12a−4w to zero.')
        N('5.7', f'Profit is P(x)=−x²+{2*a}x−1 for x≥0. Find the output x that maximizes profit.', a, 'Set P′=−2x+2a to zero; the downward-opening quadratic gives a maximum.')
        N('5.7', f'A rectangle with perimeter {8*a} m has maximum possible area. Find that area in m².', 4*a*a, 'The optimal sides are both 2a, so the area is (2a)².')
        N('5.8', f'Use one trapezoid of width {i+1}, with endpoint heights 2 and 6, to estimate area.', 4*(i+1), 'Use h(y₀+y₁)/2.')
        N('5.8', f'Use two trapezoids, each width {i}, with heights 1, 3 and 5 to estimate area.', 6*i, 'Use h[y₀+2y₁+y₂]/2.')
        N('5.8', f'An interval from 0 to {6*i} is divided into 3 equal trapezoids. Find their common width.', 2*i, 'Step width equals total interval length divided by the number of subintervals.')
        N('5.8', f'Use the trapezoidal rule with heights {i}, {i+2}, {i+4}, {i+6} and width 2 to estimate area.', 6*i+18, 'Use (2/2)[y₀+2y₁+2y₂+y₃].')
    expected = [f'{topic}.{j}' for topic,count in enumerate([8,6,6,11,8],1) for j in range(1,count+1)]
    return b.finish(expected)
